i=[[0,0,0,0],[0,0,0,0]]
i[1][0]=complex(7,1)
i[1][2]=complex(8,1)
i[1][3]=complex(6,1)
i[1][1]=complex(9,1)
k=i[1][0]
o=i[1][2]
p=i[1][3]
l=i[1][1]
ol=k.real*-k.real+o.real*-o.real+p.real*-p.real+l.real*-l.real
lo=k.imag*-k.imag+o.imag*-o.imag+p.imag*-p.imag+l.imag*-l.imag
i[0][0]=complex(5,3)
i[0][2]=complex(5,4)
i[0][3]=complex(5,5)
i[0][1]=complex(5,2)
k=i[0][0]
o=i[0][2]
p=i[0][3]
l=i[0][1]
ko=k.real*-k.real+o.real*-o.real+p.real*-p.real+l.real*-l.real
ok=k.imag*-k.imag+o.imag*-o.imag+p.imag*-p.imag+l.imag*-l.imag
ui=complex(ko,ok)
iu=complex(lo,ol)
print(ui)
print(iu)
#print(iu.real/ui.real+iu.imag/ui.imag)
op=ui.real*-ui.real
po=iu.imag*-iu.imag
print(op)
print(po)
print(po/op)
